### ISSUE TITLE
Google Assistant Support

### ISSUE THREAD

**Issue by RubbaBoy** [RubbaBoy/MSPaintIDE#20]
One annoying thing you have to do in all IDEs natively including MS Paint IDE is clicking to compile and run your code. A very useful feature to have would be Google Assistant Integration, to be used on something like a phone or a Google Home device so you could say things like "Hey Google, run my program" for a hands-off approach to development.

**Comment by AL1L** [comment]
This is absurd! I like it

**Comment by wyatt-herkamp** [comment]
> 
> 
> This is absurd! I like it

That is the goal of MSPaintIDE :)

**Comment by AL1L** [comment]
@wherkamp yes

**Comment by RubbaBoy** [comment]
Feature added, check out https://twitter.com/MSPaintIDE/status/1136785824454983680
