### ISSUE TITLE
Support Language Servers

### ISSUE THREAD

**Issue by mickaelistria** [RubbaBoy/MSPaintIDE#21]
To add more validation and more support for more languages easily, this IDE should consider adding support for language servers that rely on the language server protocol.

**Comment by RubbaBoy** [comment]
I fully agree, that's in the "to-do" list of the IDE currently. I've been working on the new website recently and it's almost done, and since I just finished the last feature I was working on, I may just add LSP support next.

The IDE wouldn't be able to take advantage of a lot of features of language servers (e.g. autocompletion) for now, but it would probably be good to have now for future updates.

**Comment by mickaelistria** [comment]
For autocompletion, I can imagine Clippy popping up and suggesting the proposals ;)
For LSP support in Java, you can use the very good LSP4J API, it's what's used successfully by all other Java IDEs.

**Comment by RubbaBoy** [comment]
Lol, I'm sure something can be figured out for that. And I'll check out that API soon, thank you

**Comment by RubbaBoy** [comment]
Do you know if there are any examples of using LSP4J as a client? I could only find the "[Getting Started](https://github.com/eclipse/lsp4j/blob/master/documentation/README.md)" page on it, and that doesn't give many details of connecting, except as a server. I got some stuff almost working, but I keep getting ```Debugger failed to attach: timeout during handshake``` on the server, if you could point me in a better direction it'd be much appreciated.

**Comment by mickaelistria** [comment]
See https://git.eclipse.org/c/lsp4e/lsp4e.git/tree/org.eclipse.lsp4e/src/org/eclipse/lsp4e/LanguageServerWrapper.java for the Eclipse IDE client code.

**Comment by RubbaBoy** [comment]
Thank you for the reference, I'm also using [LSP4IntelliJ](https://github.com/ballerina-platform/lsp4intellij) as another code reference in case anyone is interested. I have a basic example working that I will be pushing soon, but currently, it only relies on the default creation of the `jdt.ls-java-project` project and I can't seem to figure out how to make/read custom ones. Does it possibly rely on external creation of projects? Thank you for your help so far, this is probably something dumb I'm forgetting about/overlooking.

**Comment by mickaelistria** [comment]
Cc @fbricon: can you please help here?

**Comment by RubbaBoy** [comment]
I've been doing some testing and a bunch of searching around, and it seems like what other LSP clients like [vscode-java](https://github.com/redhat-developer/vscode-java) are doing is just importing a preexisting template eclipse project, from templates like from [vscode-java-dependency](https://github.com/microsoft/vscode-java-dependency/tree/0eebe84e56ae1a4671877548faa1106d049ab24c/templates). I think I will pursue this going forwards and just ignore the default package being made until I find a solution for it.

If I am doing this horribly wrong or have any general suggestions just let me know.

**Comment by RubbaBoy** [comment]
Finished implementation with 2 currently supported languages (More coming in the near future) in #23, thanks for your suggestions/help :)

**Comment by mickaelistria** [comment]
That's really great! Thanks and congrats for this development!
