### ISSUE TITLE
Gradle Integration

### ISSUE THREAD

**Issue by RubbaBoy** [RubbaBoy/MSPaintIDE#26]
The addition of Gradle would make the usage of Java projects much easier and in closer relation to other less-advanced IDEs. This will be done with Gradle's [Tooling API](https://docs.gradle.org/current/userguide/embedding.html) to run things and get dependencies. The hardest task about this will most likely be communicating these changes with the LSP Server, though from what it looks like, the Tooling API allows you to get the jars of dependencies.

### A question to others:
Should all projects be Gradle, or should it just be an option? If gradle enforcement was present, it would be easier to implement, however, not everyone may want Gradle and it would lack the necessary modularity if Maven, Bazel, etc. also wanted to be implemented.

If anyone has suggestions or would like to help with this, let me know in the comments. Following this, I would love to make a stream and/or series of programming a large application in MS Paint IDE.

**Comment by BlakeStevenson** [comment]
You could make a separate branch of the application that forces Gradle while maintaining the master branch as plain Java. Would make the implementation easier while still allowing people to use both. However, it might be a pain to continue to provide updates for both versions:

**Comment by AL1L** [comment]
@BlakeStevenson no. Just make it modular, even if it's harder to implement it will offer the best user experience.

**Comment by RubbaBoy** [comment]
@BlakeStevenson @AL1L Current I've been implementing a very modular system, which in the long term will be good, as so far it has required the ability to add modular extra language-dependent (Buildsystem-dependant as well) settings when creating projects, along with the ability to have buildsystems for any language. This will open up the ability to (fairly) easily implement things like Maven, Bazel, Ivy, etc. and BS's for other langs added in the future. Once I finish Gradle, I'll make an issue to add Maven in case someone wanted to tackle that.

**Comment by RubbaBoy** [comment]
This feature has been completed as a modular system, however it is still basic and does not support arbitrary task execution directly from the IDE. This can be done via the commandline though, and is recognized by the LSP and everything, with the ability to add more build systems to both Java and any other languages.
