### ISSUE TITLE
Dialog height is greater than monitor height

### ISSUE THREAD

**Issue by 3wayHimself** [RubbaBoy/MSPaintIDE#6]
Title basically says it all.

15.6" 1366x768

![image](https://user-images.githubusercontent.com/36007804/45000604-4d32de00-af94-11e8-8f05-adaf2ebd8fed.png)

**Comment by RubbaBoy** [comment]
Thank you for your issue, I should have this fixed sometime this week, once I finish this feature I'm working on currently.

**Comment by RubbaBoy** [comment]
This will be included in the next release (v2.2.0) coming in a few days.
